/* Generated By:JavaCC: Do not edit this line. LexConstants.java */
package teste;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int MULTIPLY = 11;
  /** RegularExpression Id. */
  int DIVIDE = 12;
  /** RegularExpression Id. */
  int LESSTHAN = 13;
  /** RegularExpression Id. */
  int MORETHAN = 14;
  /** RegularExpression Id. */
  int DIFTHAN = 15;
  /** RegularExpression Id. */
  int EQUALTHAN = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int ELSE = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int VOID = 27;
  /** RegularExpression Id. */
  int MAIN = 28;
  /** RegularExpression Id. */
  int PRINT = 29;
  /** RegularExpression Id. */
  int PAUSE = 30;
  /** RegularExpression Id. */
  int CLS = 31;
  /** RegularExpression Id. */
  int ASSIGNMENT = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int REAL = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int ESQPAR = 38;
  /** RegularExpression Id. */
  int DIRPAR = 39;
  /** RegularExpression Id. */
  int ESQCURLY = 40;
  /** RegularExpression Id. */
  int DIRCURLY = 41;
  /** RegularExpression Id. */
  int PONTOVIRGULA = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"==\"",
    "\"||\"",
    "\"&&\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"void\"",
    "\"main\"",
    "\"print\"",
    "\"pause\"",
    "\"cls\"",
    "\"=\"",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<NUM>",
    "<REAL>",
    "<STRING>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
